id: P9B964B03
initial_creation_type: ocr
source_metadata:
  volumes:
    89e62b8d3ec74835933e8c94c3bc5920:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་བསྟོད་པ་རྐང་པ་བརྒྱད་པ།
      total_pages: 1856
      volume_number: 14
